slave_db_enable: false
private_key: "cadf7450f8a7f15b5a3c9eb094b7de3fcef85465ee3de3d3a3bb687f31c79289"
num_confirmations: 10
safe_abort_nonce_too_low_count: 3
caller_address: "0x155c8B4995b43C951016eb381478714b1e7f0e83"
enable_api_cache: false
gas_oracle_endpoint: "127.0.0.1:8081"

server:
  host: 0.0.0.0
  port: 8082

metrics:
  host: 0.0.0.0
  port: 8083

rpcs:
  - rpc_url: 'https://eth-sepolia.g.alchemy.com/v2/afSCtxPWD3NE5vSjJm2GQ'
    chain_id: 11155111
    start_block: 8812552
    header_buffer_size: 500
    event_unpack_block: 8812552
    contracts:
      pool_manager_address: "0x26FF133bAC77404Fb87BFB0ce712AFdf1F41d1BE"
      message_manager_address: "0x69e00b8550a2eE6862C8Ba0DFd7d2802b2c4B345"

master_db:
  db_host: "127.0.0.1"
  db_port: 5432
  db_user: "postgres"
  db_password: "89966336"
  db_name: "flashloan_scanner"

slave_db:
  db_host: "127.0.0.1"
  db_port: 5432
  db_user: "postgres"
  db_password: "89966336"
  db_name: "flashloan_scanner"

scanner:
  enabled: true
  protocol: "balancer_v2"
  chain_id: 11155111
  run_mode: "once"
  start_block: 8812552
  end_block: 8812552
  batch_size: 500
  loop_interval_seconds: 5
  skip_tx_fetch: true
  trace_enabled: false
  aave:
    pools: []
  balancer:
    vaults:
      - "0x2222222222222222222222222222222222222222"
  uniswap_v2:
    factories: []
    pairs: []
